export const notes = {
  "GrandPiano" : {
    "Short" : [
      'PianoSBC/GrandPiano_Short - C0.mp3', 'PianoSBC/GrandPiano_Short - Csharp0.mp3',
      'PianoSBC/GrandPiano_Short - D0.mp3', 'PianoSBC/GrandPiano_Short - Dsharp0.mp3',
      'PianoSBC/GrandPiano_Short - E0.mp3',
      'PianoSBC/GrandPiano_Short - F0.mp3', 'PianoSBC/GrandPiano_Short - Fsharp0.mp3',
      'PianoSBC/GrandPiano_Short - G0.mp3', 'PianoSBC/GrandPiano_Short - Gsharp0.mp3',
      'PianoSBC/GrandPiano_Short - A0.mp3', 'PianoSBC/GrandPiano_Short - Asharp0.mp3',
      'PianoSBC/GrandPiano_Short - B0.mp3',
      'PianoSBC/GrandPiano_Short - C1.mp3', 'PianoSBC/GrandPiano_Short - Csharp1.mp3',
      'PianoSBC/GrandPiano_Short - D1.mp3', 'PianoSBC/GrandPiano_Short - Dsharp1.mp3',
      'PianoSBC/GrandPiano_Short - E1.mp3',
      'PianoSBC/GrandPiano_Short - F1.mp3', 'PianoSBC/GrandPiano_Short - Fsharp1.mp3',
      'PianoSBC/GrandPiano_Short - G1.mp3', 'PianoSBC/GrandPiano_Short - Gsharp1.mp3',
      'PianoSBC/GrandPiano_Short - A1.mp3', 'PianoSBC/GrandPiano_Short - Asharp1.mp3',
      'PianoSBC/GrandPiano_Short - B1.mp3',
      'PianoSBC/GrandPiano_Short - C2.mp3', 'PianoSBC/GrandPiano_Short - Csharp2.mp3',
      'PianoSBC/GrandPiano_Short - D2.mp3', 'PianoSBC/GrandPiano_Short - Dsharp2.mp3',
      'PianoSBC/GrandPiano_Short - E2.mp3',
      'PianoSBC/GrandPiano_Short - F2.mp3', 'PianoSBC/GrandPiano_Short - Fsharp2.mp3',
      'PianoSBC/GrandPiano_Short - G2.mp3', 'PianoSBC/GrandPiano_Short - Gsharp2.mp3',
      'PianoSBC/GrandPiano_Short - A2.mp3', 'PianoSBC/GrandPiano_Short - Asharp2.mp3',
      'PianoSBC/GrandPiano_Short - B2.mp3',
      'PianoSBC/GrandPiano_Short - C3.mp3', 'PianoSBC/GrandPiano_Short - Csharp3.mp3',
      'PianoSBC/GrandPiano_Short - D3.mp3', 'PianoSBC/GrandPiano_Short - Dsharp3.mp3',
      'PianoSBC/GrandPiano_Short - E3.mp3',
      'PianoSBC/GrandPiano_Short - F3.mp3', 'PianoSBC/GrandPiano_Short - Fsharp3.mp3',
      'PianoSBC/GrandPiano_Short - G3.mp3', 'PianoSBC/GrandPiano_Short - Gsharp3.mp3',
      'PianoSBC/GrandPiano_Short - A3.mp3', 'PianoSBC/GrandPiano_Short - Asharp3.mp3',
      'PianoSBC/GrandPiano_Short - B3.mp3',
      'PianoSBC/GrandPiano_Short - C4.mp3', 'PianoSBC/GrandPiano_Short - Csharp4.mp3',
      'PianoSBC/GrandPiano_Short - D4.mp3', 'PianoSBC/GrandPiano_Short - Dsharp4.mp3',
      'PianoSBC/GrandPiano_Short - E4.mp3',
      'PianoSBC/GrandPiano_Short - F4.mp3', 'PianoSBC/GrandPiano_Short - Fsharp4.mp3',
      'PianoSBC/GrandPiano_Short - G4.mp3', 'PianoSBC/GrandPiano_Short - Gsharp4.mp3',
      'PianoSBC/GrandPiano_Short - A4.mp3', 'PianoSBC/GrandPiano_Short - Asharp4.mp3',
      'PianoSBC/GrandPiano_Short - B4.mp3',
      'PianoSBC/GrandPiano_Short - C5.mp3', 'PianoSBC/GrandPiano_Short - Csharp5.mp3',
      'PianoSBC/GrandPiano_Short - D5.mp3', 'PianoSBC/GrandPiano_Short - Dsharp5.mp3',
      'PianoSBC/GrandPiano_Short - E5.mp3',
      'PianoSBC/GrandPiano_Short - F5.mp3', 'PianoSBC/GrandPiano_Short - Fsharp5.mp3',
      'PianoSBC/GrandPiano_Short - G5.mp3', 'PianoSBC/GrandPiano_Short - Gsharp5.mp3',
      'PianoSBC/GrandPiano_Short - A5.mp3', 'PianoSBC/GrandPiano_Short - Asharp5.mp3',
      'PianoSBC/GrandPiano_Short - B5.mp3',
      'PianoSBC/GrandPiano_Short - C6.mp3', 'PianoSBC/GrandPiano_Short - Csharp6.mp3',
      'PianoSBC/GrandPiano_Short - D6.mp3', 'PianoSBC/GrandPiano_Short - Dsharp6.mp3',
      'PianoSBC/GrandPiano_Short - E6.mp3',
      'PianoSBC/GrandPiano_Short - F6.mp3', 'PianoSBC/GrandPiano_Short - Fsharp6.mp3',
      'PianoSBC/GrandPiano_Short - G6.mp3', 'PianoSBC/GrandPiano_Short - Gsharp6.mp3',
      'PianoSBC/GrandPiano_Short - A6.mp3', 'PianoSBC/GrandPiano_Short - Asharp6.mp3',
      'PianoSBC/GrandPiano_Short - B6.mp3',
      'PianoSBC/GrandPiano_Short - C7.mp3','PianoSBC/GrandPiano_Short - Csharp7.mp3',
      'PianoSBC/GrandPiano_Short - D7.mp3', 'PianoSBC/GrandPiano_Short - Dsharp7.mp3',
      'PianoSBC/GrandPiano_Short - E7.mp3',
      'PianoSBC/GrandPiano_Short - F7.mp3', 'PianoSBC/GrandPiano_Short - Fsharp7.mp3',
      'PianoSBC/GrandPiano_Short - G7.mp3', 'PianoSBC/GrandPiano_Short - Gsharp7.mp3',
      'PianoSBC/GrandPiano_Short - A7.mp3', 'PianoSBC/GrandPiano_Short - Asharp7.mp3',
      'PianoSBC/GrandPiano_Short - B7.mp3',
      'PianoSBC/GrandPiano_Short - C8.mp3', 'PianoSBC/GrandPiano_Short - Csharp8.mp3',
      'PianoSBC/GrandPiano_Short - D8.mp3', 'PianoSBC/GrandPiano_Short - Dsharp8.mp3',
      'PianoSBC/GrandPiano_Short - E8.mp3',
      'PianoSBC/GrandPiano_Short - F8.mp3', 'PianoSBC/GrandPiano_Short - Fsharp8.mp3',
      'PianoSBC/GrandPiano_Short - G8.mp3', 'PianoSBC/GrandPiano_Short - Gsharp8.mp3',
      'PianoSBC/GrandPiano_Short - A8.mp3', 'PianoSBC/GrandPiano_Short - Asharp8.mp3',
      'PianoSBC/GrandPiano_Short - B8.mp3',
    ],

    "Medium" : [
      'PianoSBC/GrandPiano - C0.mp3', 'PianoSBC/GrandPiano - Csharp0.mp3',
      'PianoSBC/GrandPiano - D0.mp3', 'PianoSBC/GrandPiano - Dsharp0.mp3',
      'PianoSBC/GrandPiano - E0.mp3',
      'PianoSBC/GrandPiano - F0.mp3', 'PianoSBC/GrandPiano - Fsharp0.mp3',
      'PianoSBC/GrandPiano - G0.mp3', 'PianoSBC/GrandPiano - Gsharp0.mp3',
      'PianoSBC/GrandPiano - A0.mp3', 'PianoSBC/GrandPiano - Asharp0.mp3',
      'PianoSBC/GrandPiano - B0.mp3',
      'PianoSBC/GrandPiano - C1.mp3', 'PianoSBC/GrandPiano - Csharp1.mp3',
      'PianoSBC/GrandPiano - D1.mp3', 'PianoSBC/GrandPiano - Dsharp1.mp3',
      'PianoSBC/GrandPiano - E1.mp3',
      'PianoSBC/GrandPiano - F1.mp3', 'PianoSBC/GrandPiano - Fsharp1.mp3',
      'PianoSBC/GrandPiano - G1.mp3', 'PianoSBC/GrandPiano - Gsharp1.mp3',
      'PianoSBC/GrandPiano - A1.mp3', 'PianoSBC/GrandPiano - Asharp1.mp3',
      'PianoSBC/GrandPiano - B1.mp3',
      'PianoSBC/GrandPiano - C2.mp3', 'PianoSBC/GrandPiano - Csharp2.mp3',
      'PianoSBC/GrandPiano - D2.mp3', 'PianoSBC/GrandPiano - Dsharp2.mp3',
      'PianoSBC/GrandPiano - E2.mp3',
      'PianoSBC/GrandPiano - F2.mp3', 'PianoSBC/GrandPiano - Fsharp2.mp3',
      'PianoSBC/GrandPiano - G2.mp3', 'PianoSBC/GrandPiano - Gsharp2.mp3',
      'PianoSBC/GrandPiano - A2.mp3', 'PianoSBC/GrandPiano - Asharp2.mp3',
      'PianoSBC/GrandPiano - B2.mp3',
      'PianoSBC/GrandPiano - C3.mp3', 'PianoSBC/GrandPiano - Csharp3.mp3',
      'PianoSBC/GrandPiano - D3.mp3', 'PianoSBC/GrandPiano - Dsharp3.mp3',
      'PianoSBC/GrandPiano - E3.mp3',
      'PianoSBC/GrandPiano - F3.mp3', 'PianoSBC/GrandPiano - Fsharp3.mp3',
      'PianoSBC/GrandPiano - G3.mp3', 'PianoSBC/GrandPiano - Gsharp3.mp3',
      'PianoSBC/GrandPiano - A3.mp3', 'PianoSBC/GrandPiano - Asharp3.mp3',
      'PianoSBC/GrandPiano - B3.mp3',
      'PianoSBC/GrandPiano - C4.mp3', 'PianoSBC/GrandPiano - Csharp4.mp3',
      'PianoSBC/GrandPiano - D4.mp3', 'PianoSBC/GrandPiano - Dsharp4.mp3',
      'PianoSBC/GrandPiano - E4.mp3',
      'PianoSBC/GrandPiano - F4.mp3', 'PianoSBC/GrandPiano - Fsharp4.mp3',
      'PianoSBC/GrandPiano - G4.mp3', 'PianoSBC/GrandPiano - Gsharp4.mp3',
      'PianoSBC/GrandPiano - A4.mp3', 'PianoSBC/GrandPiano - Asharp4.mp3',
      'PianoSBC/GrandPiano - B4.mp3',
      'PianoSBC/GrandPiano - C5.mp3', 'PianoSBC/GrandPiano - Csharp5.mp3',
      'PianoSBC/GrandPiano - D5.mp3', 'PianoSBC/GrandPiano - Dsharp5.mp3',
      'PianoSBC/GrandPiano - E5.mp3',
      'PianoSBC/GrandPiano - F5.mp3', 'PianoSBC/GrandPiano - Fsharp5.mp3',
      'PianoSBC/GrandPiano - G5.mp3', 'PianoSBC/GrandPiano - Gsharp5.mp3',
      'PianoSBC/GrandPiano - A5.mp3', 'PianoSBC/GrandPiano - Asharp5.mp3',
      'PianoSBC/GrandPiano - B5.mp3',
      'PianoSBC/GrandPiano - C6.mp3', 'PianoSBC/GrandPiano - Csharp6.mp3',
      'PianoSBC/GrandPiano - D6.mp3', 'PianoSBC/GrandPiano - Dsharp6.mp3',
      'PianoSBC/GrandPiano - E6.mp3',
      'PianoSBC/GrandPiano - F6.mp3', 'PianoSBC/GrandPiano - Fsharp6.mp3',
      'PianoSBC/GrandPiano - G6.mp3', 'PianoSBC/GrandPiano - Gsharp6.mp3',
      'PianoSBC/GrandPiano - A6.mp3', 'PianoSBC/GrandPiano - Asharp6.mp3',
      'PianoSBC/GrandPiano - B6.mp3',
      'PianoSBC/GrandPiano - C7.mp3','PianoSBC/GrandPiano - Csharp7.mp3',
      'PianoSBC/GrandPiano - D7.mp3', 'PianoSBC/GrandPiano - Dsharp7.mp3',
      'PianoSBC/GrandPiano - E7.mp3',
      'PianoSBC/GrandPiano - F7.mp3', 'PianoSBC/GrandPiano - Fsharp7.mp3',
      'PianoSBC/GrandPiano - G7.mp3', 'PianoSBC/GrandPiano - Gsharp7.mp3',
      'PianoSBC/GrandPiano - A7.mp3', 'PianoSBC/GrandPiano - Asharp7.mp3',
      'PianoSBC/GrandPiano - B7.mp3',
      'PianoSBC/GrandPiano - C8.mp3', 'PianoSBC/GrandPiano - Csharp8.mp3',
      'PianoSBC/GrandPiano - D8.mp3', 'PianoSBC/GrandPiano - Dsharp8.mp3',
      'PianoSBC/GrandPiano - E8.mp3',
      'PianoSBC/GrandPiano - F8.mp3', 'PianoSBC/GrandPiano - Fsharp8.mp3',
      'PianoSBC/GrandPiano - G8.mp3', 'PianoSBC/GrandPiano - Gsharp8.mp3',
      'PianoSBC/GrandPiano - A8.mp3', 'PianoSBC/GrandPiano - Asharp8.mp3',
      'PianoSBC/GrandPiano - B8.mp3',

    ],

    "Long" : [

    ]

  }
}

  
 export const mappings =
  {
    'C Major': [
      36, 38, 40, 41, 43, 45, 47, 48,
      35, 37, 39, 40, 42, 44, 46, 47,
      33, 35, 37, 38, 40, 42, 44, 45,
      31, 33, 35, 36, 38, 40, 42, 43,
      29, 31, 33, 34, 36, 38, 40, 41,
      28, 30, 32, 33, 35, 37, 39, 40,
      26, 28, 30, 31, 33, 35, 37, 38,
      24, 26, 28, 29, 31, 33, 35, 36
    ],

    'Direct': [
      81, 83, 72, 74, 76, 77, 79, 81,
      81, 83, 72, 74, 76, 77, 79, 81,
      69, 71, 60, 62, 64, 65, 67, 69,
      57, 59, 48, 50, 52, 53, 55, 57,
      45, 47, 36, 38, 40, 41, 43, 45,
      33, 35, 24, 26, 28, 29, 31, 33,
      21, 23, 12, 14, 16, 17, 19, 21,
      9, 11, 0, 2, 4, 5, 7, 9
    ],

    'C Major (Middle)': [
      29, 31, 33, 34, 36, 38, 40, 41,
      28, 30, 32, 33, 35, 37, 39, 40,
      26, 28, 30, 31, 33, 35, 37, 38,
      24, 26, 28, 29, 31, 33, 35, 36,
      23, 25, 27, 28, 30, 32, 34, 35,
      21, 23, 25, 26, 28, 30, 32, 33,
      19, 21, 23, 24, 26, 28, 30, 31,
      17, 19, 21, 22, 24, 26, 28, 29
    ],
    'Circle of Fifths':[
      73, 75, 77, 78, 80, 82, 84, notes.length - 1,
      66, 68, 70, 71, 73, 75, 77, 78,
      59, 61, 63, 64, 66, 68, 70, 71,
      52, 54, 56, 57, 59, 61, 63, 64,
      45, 47, 49, 50, 52, 54, 56, 57,
      38, 40, 42, 43, 45, 47, 49, 50,
      31, 33, 35, 36, 38, 40, 42, 43,
      24, 26, 28, 29, 31, 33, 35, 36
    ],
  };

export const squares_id = [
  'A8', 'B8', 'C8', 'D8', 'E8', 'F8', 'G8', 'H8',
  'A7', 'B7', 'C7', 'D7', 'E7', 'F7', 'G7', 'H7',
  'A6', 'B6', 'C6', 'D6', 'E6', 'F6', 'G6', 'H6',
  'A5', 'B5', 'C5', 'D5', 'E5', 'F5', 'G5', 'H5',
  'A4', 'B4', 'C4', 'D4', 'E4', 'F4', 'G4', 'H4',
  'A3', 'B3', 'C3', 'D3', 'E3', 'F3', 'G3', 'H3',
  'A2', 'B2', 'C2', 'D2', 'E2', 'F2', 'G2', 'H2',
  'A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'
];
