export const notes = {
  "GrandPiano" : {
    "Short" : [
      'PianoSBC/GrandPiano_Short - C0.wav', 'PianoSBC/GrandPiano_Short - Csharp0.wav',
      'PianoSBC/GrandPiano_Short - D0.wav', 'PianoSBC/GrandPiano_Short - Dsharp0.wav',
      'PianoSBC/GrandPiano_Short - E0.wav',
      'PianoSBC/GrandPiano_Short - F0.wav', 'PianoSBC/GrandPiano_Short - Fsharp0.wav',
      'PianoSBC/GrandPiano_Short - G0.wav', 'PianoSBC/GrandPiano_Short - Gsharp0.wav',
      'PianoSBC/GrandPiano_Short - A0.wav', 'PianoSBC/GrandPiano_Short - Asharp0.wav',
      'PianoSBC/GrandPiano_Short - B0.wav',
      'PianoSBC/GrandPiano_Short - C1.wav', 'PianoSBC/GrandPiano_Short - Csharp1.wav',
      'PianoSBC/GrandPiano_Short - D1.wav', 'PianoSBC/GrandPiano_Short - Dsharp1.wav',
      'PianoSBC/GrandPiano_Short - E1.wav',
      'PianoSBC/GrandPiano_Short - F1.wav', 'PianoSBC/GrandPiano_Short - Fsharp1.wav',
      'PianoSBC/GrandPiano_Short - G1.wav', 'PianoSBC/GrandPiano_Short - Gsharp1.wav',
      'PianoSBC/GrandPiano_Short - A1.wav', 'PianoSBC/GrandPiano_Short - Asharp1.wav',
      'PianoSBC/GrandPiano_Short - B1.wav',
      'PianoSBC/GrandPiano_Short - C2.wav', 'PianoSBC/GrandPiano_Short - Csharp2.wav',
      'PianoSBC/GrandPiano_Short - D2.wav', 'PianoSBC/GrandPiano_Short - Dsharp2.wav',
      'PianoSBC/GrandPiano_Short - E2.wav',
      'PianoSBC/GrandPiano_Short - F2.wav', 'PianoSBC/GrandPiano_Short - Fsharp2.wav',
      'PianoSBC/GrandPiano_Short - G2.wav', 'PianoSBC/GrandPiano_Short - Gsharp2.wav',
      'PianoSBC/GrandPiano_Short - A2.wav', 'PianoSBC/GrandPiano_Short - Asharp2.wav',
      'PianoSBC/GrandPiano_Short - B2.wav',
      'PianoSBC/GrandPiano_Short - C3.wav', 'PianoSBC/GrandPiano_Short - Csharp3.wav',
      'PianoSBC/GrandPiano_Short - D3.wav', 'PianoSBC/GrandPiano_Short - Dsharp3.wav',
      'PianoSBC/GrandPiano_Short - E3.wav',
      'PianoSBC/GrandPiano_Short - F3.wav', 'PianoSBC/GrandPiano_Short - Fsharp3.wav',
      'PianoSBC/GrandPiano_Short - G3.wav', 'PianoSBC/GrandPiano_Short - Gsharp3.wav',
      'PianoSBC/GrandPiano_Short - A3.wav', 'PianoSBC/GrandPiano_Short - Asharp3.wav',
      'PianoSBC/GrandPiano_Short - B3.wav',
      'PianoSBC/GrandPiano_Short - C4.wav', 'PianoSBC/GrandPiano_Short - Csharp4.wav',
      'PianoSBC/GrandPiano_Short - D4.wav', 'PianoSBC/GrandPiano_Short - Dsharp4.wav',
      'PianoSBC/GrandPiano_Short - E4.wav',
      'PianoSBC/GrandPiano_Short - F4.wav', 'PianoSBC/GrandPiano_Short - Fsharp4.wav',
      'PianoSBC/GrandPiano_Short - G4.wav', 'PianoSBC/GrandPiano_Short - Gsharp4.wav',
      'PianoSBC/GrandPiano_Short - A4.wav', 'PianoSBC/GrandPiano_Short - Asharp4.wav',
      'PianoSBC/GrandPiano_Short - B4.wav',
      'PianoSBC/GrandPiano_Short - C5.wav', 'PianoSBC/GrandPiano_Short - Csharp5.wav',
      'PianoSBC/GrandPiano_Short - D5.wav', 'PianoSBC/GrandPiano_Short - Dsharp5.wav',
      'PianoSBC/GrandPiano_Short - E5.wav',
      'PianoSBC/GrandPiano_Short - F5.wav', 'PianoSBC/GrandPiano_Short - Fsharp5.wav',
      'PianoSBC/GrandPiano_Short - G5.wav', 'PianoSBC/GrandPiano_Short - Gsharp5.wav',
      'PianoSBC/GrandPiano_Short - A5.wav', 'PianoSBC/GrandPiano_Short - Asharp5.wav',
      'PianoSBC/GrandPiano_Short - B5.wav',
      'PianoSBC/GrandPiano_Short - C6.wav', 'PianoSBC/GrandPiano_Short - Csharp6.wav',
      'PianoSBC/GrandPiano_Short - D6.wav', 'PianoSBC/GrandPiano_Short - Dsharp6.wav',
      'PianoSBC/GrandPiano_Short - E6.wav',
      'PianoSBC/GrandPiano_Short - F6.wav', 'PianoSBC/GrandPiano_Short - Fsharp6.wav',
      'PianoSBC/GrandPiano_Short - G6.wav', 'PianoSBC/GrandPiano_Short - Gsharp6.wav',
      'PianoSBC/GrandPiano_Short - A6.wav', 'PianoSBC/GrandPiano_Short - Asharp6.wav',
      'PianoSBC/GrandPiano_Short - B6.wav',
      'PianoSBC/GrandPiano_Short - C7.wav','PianoSBC/GrandPiano_Short - Csharp7.wav',
      'PianoSBC/GrandPiano_Short - D7.wav', 'PianoSBC/GrandPiano_Short - Dsharp7.wav',
      'PianoSBC/GrandPiano_Short - E7.wav',
      'PianoSBC/GrandPiano_Short - F7.wav', 'PianoSBC/GrandPiano_Short - Fsharp7.wav',
      'PianoSBC/GrandPiano_Short - G7.wav', 'PianoSBC/GrandPiano_Short - Gsharp7.wav',
      'PianoSBC/GrandPiano_Short - A7.wav', 'PianoSBC/GrandPiano_Short - Asharp7.wav',
      'PianoSBC/GrandPiano_Short - B7.wav',
      'PianoSBC/GrandPiano_Short - C8.wav', 'PianoSBC/GrandPiano_Short - Csharp8.wav',
      'PianoSBC/GrandPiano_Short - D8.wav', 'PianoSBC/GrandPiano_Short - Dsharp8.wav',
      'PianoSBC/GrandPiano_Short - E8.wav',
      'PianoSBC/GrandPiano_Short - F8.wav', 'PianoSBC/GrandPiano_Short - Fsharp8.wav',
      'PianoSBC/GrandPiano_Short - G8.wav', 'PianoSBC/GrandPiano_Short - Gsharp8.wav',
      'PianoSBC/GrandPiano_Short - A8.wav', 'PianoSBC/GrandPiano_Short - Asharp8.wav',
      'PianoSBC/GrandPiano_Short - B8.wav',
    ],

    "Medium" : [
      'PianoSBC/GrandPiano - C0.wav', 'PianoSBC/GrandPiano - Csharp0.wav',
      'PianoSBC/GrandPiano - D0.wav', 'PianoSBC/GrandPiano - Dsharp0.wav',
      'PianoSBC/GrandPiano - E0.wav',
      'PianoSBC/GrandPiano - F0.wav', 'PianoSBC/GrandPiano - Fsharp0.wav',
      'PianoSBC/GrandPiano - G0.wav', 'PianoSBC/GrandPiano - Gsharp0.wav',
      'PianoSBC/GrandPiano - A0.wav', 'PianoSBC/GrandPiano - Asharp0.wav',
      'PianoSBC/GrandPiano - B0.wav',
      'PianoSBC/GrandPiano - C1.wav', 'PianoSBC/GrandPiano - Csharp1.wav',
      'PianoSBC/GrandPiano - D1.wav', 'PianoSBC/GrandPiano - Dsharp1.wav',
      'PianoSBC/GrandPiano - E1.wav',
      'PianoSBC/GrandPiano - F1.wav', 'PianoSBC/GrandPiano - Fsharp1.wav',
      'PianoSBC/GrandPiano - G1.wav', 'PianoSBC/GrandPiano - Gsharp1.wav',
      'PianoSBC/GrandPiano - A1.wav', 'PianoSBC/GrandPiano - Asharp1.wav',
      'PianoSBC/GrandPiano - B1.wav',
      'PianoSBC/GrandPiano - C2.wav', 'PianoSBC/GrandPiano - Csharp2.wav',
      'PianoSBC/GrandPiano - D2.wav', 'PianoSBC/GrandPiano - Dsharp2.wav',
      'PianoSBC/GrandPiano - E2.wav',
      'PianoSBC/GrandPiano - F2.wav', 'PianoSBC/GrandPiano - Fsharp2.wav',
      'PianoSBC/GrandPiano - G2.wav', 'PianoSBC/GrandPiano - Gsharp2.wav',
      'PianoSBC/GrandPiano - A2.wav', 'PianoSBC/GrandPiano - Asharp2.wav',
      'PianoSBC/GrandPiano - B2.wav',
      'PianoSBC/GrandPiano - C3.wav', 'PianoSBC/GrandPiano - Csharp3.wav',
      'PianoSBC/GrandPiano - D3.wav', 'PianoSBC/GrandPiano - Dsharp3.wav',
      'PianoSBC/GrandPiano - E3.wav',
      'PianoSBC/GrandPiano - F3.wav', 'PianoSBC/GrandPiano - Fsharp3.wav',
      'PianoSBC/GrandPiano - G3.wav', 'PianoSBC/GrandPiano - Gsharp3.wav',
      'PianoSBC/GrandPiano - A3.wav', 'PianoSBC/GrandPiano - Asharp3.wav',
      'PianoSBC/GrandPiano - B3.wav',
      'PianoSBC/GrandPiano - C4.wav', 'PianoSBC/GrandPiano - Csharp4.wav',
      'PianoSBC/GrandPiano - D4.wav', 'PianoSBC/GrandPiano - Dsharp4.wav',
      'PianoSBC/GrandPiano - E4.wav',
      'PianoSBC/GrandPiano - F4.wav', 'PianoSBC/GrandPiano - Fsharp4.wav',
      'PianoSBC/GrandPiano - G4.wav', 'PianoSBC/GrandPiano - Gsharp4.wav',
      'PianoSBC/GrandPiano - A4.wav', 'PianoSBC/GrandPiano - Asharp4.wav',
      'PianoSBC/GrandPiano - B4.wav',
      'PianoSBC/GrandPiano - C5.wav', 'PianoSBC/GrandPiano - Csharp5.wav',
      'PianoSBC/GrandPiano - D5.wav', 'PianoSBC/GrandPiano - Dsharp5.wav',
      'PianoSBC/GrandPiano - E5.wav',
      'PianoSBC/GrandPiano - F5.wav', 'PianoSBC/GrandPiano - Fsharp5.wav',
      'PianoSBC/GrandPiano - G5.wav', 'PianoSBC/GrandPiano - Gsharp5.wav',
      'PianoSBC/GrandPiano - A5.wav', 'PianoSBC/GrandPiano - Asharp5.wav',
      'PianoSBC/GrandPiano - B5.wav',
      'PianoSBC/GrandPiano - C6.wav', 'PianoSBC/GrandPiano - Csharp6.wav',
      'PianoSBC/GrandPiano - D6.wav', 'PianoSBC/GrandPiano - Dsharp6.wav',
      'PianoSBC/GrandPiano - E6.wav',
      'PianoSBC/GrandPiano - F6.wav', 'PianoSBC/GrandPiano - Fsharp6.wav',
      'PianoSBC/GrandPiano - G6.wav', 'PianoSBC/GrandPiano - Gsharp6.wav',
      'PianoSBC/GrandPiano - A6.wav', 'PianoSBC/GrandPiano - Asharp6.wav',
      'PianoSBC/GrandPiano - B6.wav',
      'PianoSBC/GrandPiano - C7.wav','PianoSBC/GrandPiano - Csharp7.wav',
      'PianoSBC/GrandPiano - D7.wav', 'PianoSBC/GrandPiano - Dsharp7.wav',
      'PianoSBC/GrandPiano - E7.wav',
      'PianoSBC/GrandPiano - F7.wav', 'PianoSBC/GrandPiano - Fsharp7.wav',
      'PianoSBC/GrandPiano - G7.wav', 'PianoSBC/GrandPiano - Gsharp7.wav',
      'PianoSBC/GrandPiano - A7.wav', 'PianoSBC/GrandPiano - Asharp7.wav',
      'PianoSBC/GrandPiano - B7.wav',
      'PianoSBC/GrandPiano - C8.wav', 'PianoSBC/GrandPiano - Csharp8.wav',
      'PianoSBC/GrandPiano - D8.wav', 'PianoSBC/GrandPiano - Dsharp8.wav',
      'PianoSBC/GrandPiano - E8.wav',
      'PianoSBC/GrandPiano - F8.wav', 'PianoSBC/GrandPiano - Fsharp8.wav',
      'PianoSBC/GrandPiano - G8.wav', 'PianoSBC/GrandPiano - Gsharp8.wav',
      'PianoSBC/GrandPiano - A8.wav', 'PianoSBC/GrandPiano - Asharp8.wav',
      'PianoSBC/GrandPiano - B8.wav',

    ],

    "Long" : [

    ]

  },

  "GrandPiano2" : {
    "Short" : [
      'PianoSBC/GrandPiano2_Short - C0.wav', 'PianoSBC/GrandPiano2_Short - Csharp0.wav',
      'PianoSBC/GrandPiano2_Short - D0.wav', 'PianoSBC/GrandPiano2_Short - Dsharp0.wav',
      'PianoSBC/GrandPiano2_Short - E0.wav',
      'PianoSBC/GrandPiano2_Short - F0.wav', 'PianoSBC/GrandPiano2_Short - Fsharp0.wav',
      'PianoSBC/GrandPiano2_Short - G0.wav', 'PianoSBC/GrandPiano2_Short - Gsharp0.wav',
      'PianoSBC/GrandPiano2_Short - A0.wav', 'PianoSBC/GrandPiano2_Short - Asharp0.wav',
      'PianoSBC/GrandPiano2_Short - B0.wav',
      'PianoSBC/GrandPiano2_Short - C1.wav', 'PianoSBC/GrandPiano2_Short - Csharp1.wav',
      'PianoSBC/GrandPiano2_Short - D1.wav', 'PianoSBC/GrandPiano2_Short - Dsharp1.wav',
      'PianoSBC/GrandPiano2_Short - E1.wav',
      'PianoSBC/GrandPiano2_Short - F1.wav', 'PianoSBC/GrandPiano2_Short - Fsharp1.wav',
      'PianoSBC/GrandPiano2_Short - G1.wav', 'PianoSBC/GrandPiano2_Short - Gsharp1.wav',
      'PianoSBC/GrandPiano2_Short - A1.wav', 'PianoSBC/GrandPiano2_Short - Asharp1.wav',
      'PianoSBC/GrandPiano2_Short - B1.wav',
      'PianoSBC/GrandPiano2_Short - C2.wav', 'PianoSBC/GrandPiano2_Short - Csharp2.wav',
      'PianoSBC/GrandPiano2_Short - D2.wav', 'PianoSBC/GrandPiano2_Short - Dsharp2.wav',
      'PianoSBC/GrandPiano2_Short - E2.wav',
      'PianoSBC/GrandPiano2_Short - F2.wav', 'PianoSBC/GrandPiano2_Short - Fsharp2.wav',
      'PianoSBC/GrandPiano2_Short - G2.wav', 'PianoSBC/GrandPiano2_Short - Gsharp2.wav',
      'PianoSBC/GrandPiano2_Short - A2.wav', 'PianoSBC/GrandPiano2_Short - Asharp2.wav',
      'PianoSBC/GrandPiano2_Short - B2.wav',
      'PianoSBC/GrandPiano2_Short - C3.wav', 'PianoSBC/GrandPiano2_Short - Csharp3.wav',
      'PianoSBC/GrandPiano2_Short - D3.wav', 'PianoSBC/GrandPiano2_Short - Dsharp3.wav',
      'PianoSBC/GrandPiano2_Short - E3.wav',
      'PianoSBC/GrandPiano2_Short - F3.wav', 'PianoSBC/GrandPiano2_Short - Fsharp3.wav',
      'PianoSBC/GrandPiano2_Short - G3.wav', 'PianoSBC/GrandPiano2_Short - Gsharp3.wav',
      'PianoSBC/GrandPiano2_Short - A3.wav', 'PianoSBC/GrandPiano2_Short - Asharp3.wav',
      'PianoSBC/GrandPiano2_Short - B3.wav',
      'PianoSBC/GrandPiano2_Short - C4.wav', 'PianoSBC/GrandPiano2_Short - Csharp4.wav',
      'PianoSBC/GrandPiano2_Short - D4.wav', 'PianoSBC/GrandPiano2_Short - Dsharp4.wav',
      'PianoSBC/GrandPiano2_Short - E4.wav',
      'PianoSBC/GrandPiano2_Short - F4.wav', 'PianoSBC/GrandPiano2_Short - Fsharp4.wav',
      'PianoSBC/GrandPiano2_Short - G4.wav', 'PianoSBC/GrandPiano2_Short - Gsharp4.wav',
      'PianoSBC/GrandPiano2_Short - A4.wav', 'PianoSBC/GrandPiano2_Short - Asharp4.wav',
      'PianoSBC/GrandPiano2_Short - B4.wav',
      'PianoSBC/GrandPiano2_Short - C5.wav', 'PianoSBC/GrandPiano2_Short - Csharp5.wav',
      'PianoSBC/GrandPiano2_Short - D5.wav', 'PianoSBC/GrandPiano2_Short - Dsharp5.wav',
      'PianoSBC/GrandPiano2_Short - E5.wav',
      'PianoSBC/GrandPiano2_Short - F5.wav', 'PianoSBC/GrandPiano2_Short - Fsharp5.wav',
      'PianoSBC/GrandPiano2_Short - G5.wav', 'PianoSBC/GrandPiano2_Short - Gsharp5.wav',
      'PianoSBC/GrandPiano2_Short - A5.wav', 'PianoSBC/GrandPiano2_Short - Asharp5.wav',
      'PianoSBC/GrandPiano2_Short - B5.wav',
      'PianoSBC/GrandPiano2_Short - C6.wav', 'PianoSBC/GrandPiano2_Short - Csharp6.wav',
      'PianoSBC/GrandPiano2_Short - D6.wav', 'PianoSBC/GrandPiano2_Short - Dsharp6.wav',
      'PianoSBC/GrandPiano2_Short - E6.wav',
      'PianoSBC/GrandPiano2_Short - F6.wav', 'PianoSBC/GrandPiano2_Short - Fsharp6.wav',
      'PianoSBC/GrandPiano2_Short - G6.wav', 'PianoSBC/GrandPiano2_Short - Gsharp6.wav',
      'PianoSBC/GrandPiano2_Short - A6.wav', 'PianoSBC/GrandPiano2_Short - Asharp6.wav',
      'PianoSBC/GrandPiano2_Short - B6.wav',
      'PianoSBC/GrandPiano2_Short - C7.wav','PianoSBC/GrandPiano2_Short - Csharp7.wav',
      'PianoSBC/GrandPiano2_Short - D7.wav', 'PianoSBC/GrandPiano2_Short - Dsharp7.wav',
      'PianoSBC/GrandPiano2_Short - E7.wav',
      'PianoSBC/GrandPiano2_Short - F7.wav', 'PianoSBC/GrandPiano2_Short - Fsharp7.wav',
      'PianoSBC/GrandPiano2_Short - G7.wav', 'PianoSBC/GrandPiano2_Short - Gsharp7.wav',
      'PianoSBC/GrandPiano2_Short - A7.wav', 'PianoSBC/GrandPiano2_Short - Asharp7.wav',
      'PianoSBC/GrandPiano2_Short - B7.wav',
      'PianoSBC/GrandPiano2_Short - C8.wav', 'PianoSBC/GrandPiano2_Short - Csharp8.wav',
      'PianoSBC/GrandPiano2_Short - D8.wav', 'PianoSBC/GrandPiano2_Short - Dsharp8.wav',
      'PianoSBC/GrandPiano2_Short - E8.wav',
      'PianoSBC/GrandPiano2_Short - F8.wav', 'PianoSBC/GrandPiano2_Short - Fsharp8.wav',
      'PianoSBC/GrandPiano2_Short - G8.wav', 'PianoSBC/GrandPiano2_Short - Gsharp8.wav',
      'PianoSBC/GrandPiano2_Short - A8.wav', 'PianoSBC/GrandPiano2_Short - Asharp8.wav',
      'PianoSBC/GrandPiano2_Short - B8.wav',
    ],

    "Medium" : [
      'PianoSBC/GrandPiano2 - C0.wav', 'PianoSBC/GrandPiano2 - Csharp0.wav',
      'PianoSBC/GrandPiano2 - D0.wav', 'PianoSBC/GrandPiano2 - Dsharp0.wav',
      'PianoSBC/GrandPiano2 - E0.wav',
      'PianoSBC/GrandPiano2 - F0.wav', 'PianoSBC/GrandPiano2 - Fsharp0.wav',
      'PianoSBC/GrandPiano2 - G0.wav', 'PianoSBC/GrandPiano2 - Gsharp0.wav',
      'PianoSBC/GrandPiano2 - A0.wav', 'PianoSBC/GrandPiano2 - Asharp0.wav',
      'PianoSBC/GrandPiano2 - B0.wav',
      'PianoSBC/GrandPiano2 - C1.wav', 'PianoSBC/GrandPiano2 - Csharp1.wav',
      'PianoSBC/GrandPiano2 - D1.wav', 'PianoSBC/GrandPiano2 - Dsharp1.wav',
      'PianoSBC/GrandPiano2 - E1.wav',
      'PianoSBC/GrandPiano2 - F1.wav', 'PianoSBC/GrandPiano2 - Fsharp1.wav',
      'PianoSBC/GrandPiano2 - G1.wav', 'PianoSBC/GrandPiano2 - Gsharp1.wav',
      'PianoSBC/GrandPiano2 - A1.wav', 'PianoSBC/GrandPiano2 - Asharp1.wav',
      'PianoSBC/GrandPiano2 - B1.wav',
      'PianoSBC/GrandPiano2 - C2.wav', 'PianoSBC/GrandPiano2 - Csharp2.wav',
      'PianoSBC/GrandPiano2 - D2.wav', 'PianoSBC/GrandPiano2 - Dsharp2.wav',
      'PianoSBC/GrandPiano2 - E2.wav',
      'PianoSBC/GrandPiano2 - F2.wav', 'PianoSBC/GrandPiano2 - Fsharp2.wav',
      'PianoSBC/GrandPiano2 - G2.wav', 'PianoSBC/GrandPiano2 - Gsharp2.wav',
      'PianoSBC/GrandPiano2 - A2.wav', 'PianoSBC/GrandPiano2 - Asharp2.wav',
      'PianoSBC/GrandPiano2 - B2.wav',
      'PianoSBC/GrandPiano2 - C3.wav', 'PianoSBC/GrandPiano2 - Csharp3.wav',
      'PianoSBC/GrandPiano2 - D3.wav', 'PianoSBC/GrandPiano2 - Dsharp3.wav',
      'PianoSBC/GrandPiano2 - E3.wav',
      'PianoSBC/GrandPiano2 - F3.wav', 'PianoSBC/GrandPiano2 - Fsharp3.wav',
      'PianoSBC/GrandPiano2 - G3.wav', 'PianoSBC/GrandPiano2 - Gsharp3.wav',
      'PianoSBC/GrandPiano2 - A3.wav', 'PianoSBC/GrandPiano2 - Asharp3.wav',
      'PianoSBC/GrandPiano2 - B3.wav',
      'PianoSBC/GrandPiano2 - C4.wav', 'PianoSBC/GrandPiano2 - Csharp4.wav',
      'PianoSBC/GrandPiano2 - D4.wav', 'PianoSBC/GrandPiano2 - Dsharp4.wav',
      'PianoSBC/GrandPiano2 - E4.wav',
      'PianoSBC/GrandPiano2 - F4.wav', 'PianoSBC/GrandPiano2 - Fsharp4.wav',
      'PianoSBC/GrandPiano2 - G4.wav', 'PianoSBC/GrandPiano2 - Gsharp4.wav',
      'PianoSBC/GrandPiano2 - A4.wav', 'PianoSBC/GrandPiano2 - Asharp4.wav',
      'PianoSBC/GrandPiano2 - B4.wav',
      'PianoSBC/GrandPiano2 - C5.wav', 'PianoSBC/GrandPiano2 - Csharp5.wav',
      'PianoSBC/GrandPiano2 - D5.wav', 'PianoSBC/GrandPiano2 - Dsharp5.wav',
      'PianoSBC/GrandPiano2 - E5.wav',
      'PianoSBC/GrandPiano2 - F5.wav', 'PianoSBC/GrandPiano2 - Fsharp5.wav',
      'PianoSBC/GrandPiano2 - G5.wav', 'PianoSBC/GrandPiano2 - Gsharp5.wav',
      'PianoSBC/GrandPiano2 - A5.wav', 'PianoSBC/GrandPiano2 - Asharp5.wav',
      'PianoSBC/GrandPiano2 - B5.wav',
      'PianoSBC/GrandPiano2 - C6.wav', 'PianoSBC/GrandPiano2 - Csharp6.wav',
      'PianoSBC/GrandPiano2 - D6.wav', 'PianoSBC/GrandPiano2 - Dsharp6.wav',
      'PianoSBC/GrandPiano2 - E6.wav',
      'PianoSBC/GrandPiano2 - F6.wav', 'PianoSBC/GrandPiano2 - Fsharp6.wav',
      'PianoSBC/GrandPiano2 - G6.wav', 'PianoSBC/GrandPiano2 - Gsharp6.wav',
      'PianoSBC/GrandPiano2 - A6.wav', 'PianoSBC/GrandPiano2 - Asharp6.wav',
      'PianoSBC/GrandPiano2 - B6.wav',
      'PianoSBC/GrandPiano2 - C7.wav','PianoSBC/GrandPiano2 - Csharp7.wav',
      'PianoSBC/GrandPiano2 - D7.wav', 'PianoSBC/GrandPiano2 - Dsharp7.wav',
      'PianoSBC/GrandPiano2 - E7.wav',
      'PianoSBC/GrandPiano2 - F7.wav', 'PianoSBC/GrandPiano2 - Fsharp7.wav',
      'PianoSBC/GrandPiano2 - G7.wav', 'PianoSBC/GrandPiano2 - Gsharp7.wav',
      'PianoSBC/GrandPiano2 - A7.wav', 'PianoSBC/GrandPiano2 - Asharp7.wav',
      'PianoSBC/GrandPiano2 - B7.wav',
      'PianoSBC/GrandPiano2 - C8.wav', 'PianoSBC/GrandPiano2 - Csharp8.wav',
      'PianoSBC/GrandPiano2 - D8.wav', 'PianoSBC/GrandPiano2 - Dsharp8.wav',
      'PianoSBC/GrandPiano2 - E8.wav',
      'PianoSBC/GrandPiano2 - F8.wav', 'PianoSBC/GrandPiano2 - Fsharp8.wav',
      'PianoSBC/GrandPiano2 - G8.wav', 'PianoSBC/GrandPiano2 - Gsharp8.wav',
      'PianoSBC/GrandPiano2 - A8.wav', 'PianoSBC/GrandPiano2 - Asharp8.wav',
      'PianoSBC/GrandPiano2 - B8.wav',

    ],

    "Long" : [

    ]

  }
}

  
 export const mappings =
  {
    'C Major': [
      36, 38, 40, 41, 43, 45, 47, 48,
      35, 37, 39, 40, 42, 44, 46, 47,
      33, 35, 37, 38, 40, 42, 44, 45,
      31, 33, 35, 36, 38, 40, 42, 43,
      29, 31, 33, 34, 36, 38, 40, 41,
      28, 30, 32, 33, 35, 37, 39, 40,
      26, 28, 30, 31, 33, 35, 37, 38,
      24, 26, 28, 29, 31, 33, 35, 36
    ],

    'Direct': [
      105, 107, 96, 98, 100, 101, 103, 105,
      93, 95, 84, 86, 88, 89, 91, 93,
      81, 83, 72, 74, 76, 77, 79, 81,
      69, 71, 60, 62, 64, 65, 67, 69,
      57, 59, 48, 50, 52, 53, 55, 57,
      45, 47, 36, 38, 40, 41, 43, 45,
      33, 35, 24, 26, 28, 29, 31, 33,
      21, 23, 12, 14, 16, 17, 19, 21,
    ],

    'C Major (Middle)': [
      29, 31, 33, 34, 36, 38, 40, 41,
      28, 30, 32, 33, 35, 37, 39, 40,
      26, 28, 30, 31, 33, 35, 37, 38,
      24, 26, 28, 29, 31, 33, 35, 36,
      23, 25, 27, 28, 30, 32, 34, 35,
      21, 23, 25, 26, 28, 30, 32, 33,
      19, 21, 23, 24, 26, 28, 30, 31,
      17, 19, 21, 22, 24, 26, 28, 29
    ].map((x) => x + 12)
    ,
    'Circle of Fifths':[
      73, 75, 77, 78, 80, 82, 84, 85,
      66, 68, 70, 71, 73, 75, 77, 78,
      59, 61, 63, 64, 66, 68, 70, 71,
      52, 54, 56, 57, 59, 61, 63, 64,
      45, 47, 49, 50, 52, 54, 56, 57,
      38, 40, 42, 43, 45, 47, 49, 50,
      31, 33, 35, 36, 38, 40, 42, 43,
      24, 26, 28, 29, 31, 33, 35, 36
    ].map((x) => x + 12),
  };

export const squares_id = [
  'A8', 'B8', 'C8', 'D8', 'E8', 'F8', 'G8', 'H8',
  'A7', 'B7', 'C7', 'D7', 'E7', 'F7', 'G7', 'H7',
  'A6', 'B6', 'C6', 'D6', 'E6', 'F6', 'G6', 'H6',
  'A5', 'B5', 'C5', 'D5', 'E5', 'F5', 'G5', 'H5',
  'A4', 'B4', 'C4', 'D4', 'E4', 'F4', 'G4', 'H4',
  'A3', 'B3', 'C3', 'D3', 'E3', 'F3', 'G3', 'H3',
  'A2', 'B2', 'C2', 'D2', 'E2', 'F2', 'G2', 'H2',
  'A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'
];
